// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIMMISiujG0PGhUzFQRxTzoc16ToDO4I',
    appId: '1:348129543233:web:2443bbf7197571eb3df2c0',
    messagingSenderId: '348129543233',
    projectId: 'movielingo-717e0',
    authDomain: 'movielingo-717e0.firebaseapp.com',
    storageBucket: 'movielingo-717e0.appspot.com',
    measurementId: 'G-VPRWT9F3H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGaN0pwAk60uf2bTr4fZ8FXI8G5cMHwU8',
    appId: '1:348129543233:android:24ce6d7a72a5a73f3df2c0',
    messagingSenderId: '348129543233',
    projectId: 'movielingo-717e0',
    storageBucket: 'movielingo-717e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdy3ZpypzTzry_QKg04UOuZoDQEGOWns',
    appId: '1:348129543233:ios:c74e7f0c5824eeb83df2c0',
    messagingSenderId: '348129543233',
    projectId: 'movielingo-717e0',
    storageBucket: 'movielingo-717e0.appspot.com',
    iosBundleId: 'com.example.movielingoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdy3ZpypzTzry_QKg04UOuZoDQEGOWns',
    appId: '1:348129543233:ios:dcf5c6fe75bc3a943df2c0',
    messagingSenderId: '348129543233',
    projectId: 'movielingo-717e0',
    storageBucket: 'movielingo-717e0.appspot.com',
    iosBundleId: 'com.example.movielingoApp.RunnerTests',
  );
}
